### ISSUE TITLE
Sharing via Yatse remote is not working

### ISSUE THREAD

**Issue by jaylinski** [jaylinski/kodi-addon-soundcloud#13]
### Todo
* find out how the plugin is called if a soundcloud song is shared via Yatse (app and browser)
* handle the call in the plugin

Refs:
* https://community.soundcloud.com/desktop-230066/can-t-login-on-soundcloud-on-kodi-krypton-7385618/index2.html#post18076004
* https://forum.kodi.tv/showthread.php?tid=206635&pid=2865890#pid2865890

**Comment by moorhexa** [comment]
Neither Kore nore Yatse can share. I tried to figure it out yesterday.
Logfile while using Yatse:

`                                            Error Contents: ApiV2 JSON seems to be invalid
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.soundcloud/addon.py", line 3, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/plugin.audio.soundcloud/resources/plugin.py", line 104, in run
                                                collection = listItems.from_collection(api.resolve_url(url))
                                              File "/home/osmc/.kodi/addons/plugin.audio.soundcloud/resources/lib/soundcloud/api_v2.py", line 70, in resolve_url
                                                return self._map_json_to_collection(res)
                                              File "/home/osmc/.kodi/addons/plugin.audio.soundcloud/resources/lib/soundcloud/api_v2.py", line 201, in _map_json_to_collec
tion
                                                raise RuntimeError("ApiV2 JSON seems to be invalid")
                                            RuntimeError: ApiV2 JSON seems to be invalid
`
With curl -v 'http://api.soundcloud.com/resolve?url=https://soundcloud.com/artist/track&client_id=xxx' it returns this JSON:
`{"status":"302 - Found","location":"https://api.soundcloud.com/tracks/123?client_id=xxx"}`
curl -v 'http://api.soundcloud.com/tracks/123&client_id=xxx' returns 401 Unauthorized

**Comment by jaylinski** [comment]
> Neither Kore nore Yatse can share. I tried to figure it out yesterday.
> Logfile while using Yatse:
> 
> ` Error Contents: ApiV2 JSON seems to be invalid Traceback (most recent call last): File "/home/osmc/.kodi/addons/plugin.audio.soundcloud/addon.py", line 3, in <module> plugin.run() File "/home/osmc/.kodi/addons/plugin.audio.soundcloud/resources/plugin.py", line 104, in run collection = listItems.from_collection(api.resolve_url(url)) File "/home/osmc/.kodi/addons/plugin.audio.soundcloud/resources/lib/soundcloud/api_v2.py", line 70, in resolve_url return self._map_json_to_collection(res) File "/home/osmc/.kodi/addons/plugin.audio.soundcloud/resources/lib/soundcloud/api_v2.py", line 201, in _map_json_to_collec tion raise RuntimeError("ApiV2 JSON seems to be invalid") RuntimeError: ApiV2 JSON seems to be invalid`
> With curl -v 'http://api.soundcloud.com/resolve?url=https://soundcloud.com/artist/track&client_id=xxx' it returns this JSON:
> `{"status":"302 - Found","location":"https://api.soundcloud.com/tracks/123?client_id=xxx"}`
> curl -v 'http://api.soundcloud.com/tracks/123&client_id=xxx' returns 401 Unauthorized

@moorhexa Thx for the debug log! I think there should be an easy fix. I will take a look at it this week.

**Comment by efirshik** [comment]
send via chrome extensions ""Play to Kodi
`2019-07-02 00:40:29.078 T:1937846288   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.audio.soundcloud/play/?audio_id=300297076]`

**Comment by jaylinski** [comment]
> share to kodi with chrome extensions "Play to Kodi", log:
> `2019-07-02 00:40:29.078 T:1937846288 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.audio.soundcloud/play/?audio_id=300297076]`

@efirshik Thanks for the report. I created a separate issue for this and will look into it this week.
