### ISSUE TITLE
Playback stops after 30 minutes

### ISSUE THREAD

**Issue by moorhexa** [jaylinski/kodi-addon-soundcloud#19]
When listening to long tracks, playback stops, stutters and continues with next track in playlist.
Debug log:
`2019-07-17 17:17:51.783 T:3384304352   DEBUG: ffmpeg[C9B862E0]: [hls,applehttp] keepalive request failed for 'https://cf-hls-opus-media.sndcdn.com/media/15396217/15481039/8DR1SEuVpEra.64.opus?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1vcHVzLW1lZGlhLnNuZGNkbi5jb20vbWVkaWEvKi8qLzhEUjFTRXVWcEVyYS42NC5vcHVzIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTYzMzc2NjY5fX19XX0_&Signature=FjhVBnOJityLktgiWIaANnL-h9yF8sBRhTtOFuGJTML81r5TZ8C18pga27rahowsOlY9Hl4o0zSSQkXX1zes3GKgtJwmNCDdU43wqX5co4tBbpin99Uyzclbafw-lC9uUx8biwoqKqL0rXrasLkSn6tIMmgMEWl2gRhmxYYHJsQBa21wFF5jyukJAzZrTY~H1ubV3TNDP-v-4e~q~WrLw2Svl84p7Zat5AOpM4ZA3oihkAkoqjQmtRPOO8-nP9H4Nslh3PmoiuoXYKnS2BZJWJfhGktid8BamAKt9CjoHYd~JYzZNW2SPbp7ekMB7nB7DcNkOc1b~jWUywc9XOoDgg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ', retrying with new connection: Server returned 403 Forbidden (access denied)
2019-07-17 17:17:51.948 T:3384304352   DEBUG: ffmpeg[C9B862E0]: [https] HTTP error 403 Forbidden
2019-07-17 17:17:51.959 T:3384304352   DEBUG: ffmpeg[C9B862E0]: [hls,applehttp] Failed to open segment 183 of playlist 0
2019-07-17 17:17:54.882 T:3384304352   DEBUG: ffmpeg[C9B862E0]: [https] HTTP error 403 Forbidden
`

**Comment by jaylinski** [comment]
I'm not sure if this can be fixed by the plugin, since it simply hands over an m3u-file to the Kodi player.

@moorhexa If you wan't you can try to switch from `opus` to `mp3` codec in the advanced settings and check if the problem still occurs.

**Comment by jaylinski** [comment]
The `m3u8`-file for a one hour track consists out of 363 single segments. But I couldn't find any limiting constraints in the XBMC code. I also tried to play the `m3u8`-file with the onboard Ubuntu player, which also stopped in the middle of the playlist. So this is probably not a Kodi bug.

I'm suspecting that this is a session timeout (30min) issue on the SoundCloud end. I played the 1 hour track on the SoundCloud website and recorded the network requests. After about 30 minutes the segment requests will return a `403 Forbidden` error (like in your debug log), the SoundCloud website then simply downloads the `m3u8`-playlist again. The file will contain fresh keys and which can be played again.

Concerning a fix: I'm not sure if this should be done in Kodi or in the plugin. :thinking:

**Comment by jaylinski** [comment]
Corresponding Kodi thread: https://forum.kodi.tv/showthread.php?tid=346347

**Comment by jaylinski** [comment]
This is apparently a FFmpeg "bug" (Kodi uses FFmpeg to play HLS streams).

Maybe it helps to make the mp3 progessive transcoding an option as a workaround. I'll try that as soon as I have time.

**Comment by jaylinski** [comment]
Yep, the mp3 progessive transcoding plays the whole track. I will change the default transcoding to mp3 progessive (after some more testing).

**Comment by alejandrofo** [comment]
Where can I find "advanced settings" to change the codec? The plugin has no settings at all in my installation.

**Comment by jaylinski** [comment]
@alejandrofo Please verify you have installed version 3.2.0.

There are three ways to open the settings:
1. Open the plugin and click on the last item named "Settings"
2. Open the plugin and open the sidebar by clicking the "left arrow" and select "Add-on settings"
2. "Right click" on the plugin icon an select "Configure"

The codec setting (named `Streaming`) is now in the "General" settings tab.
