### ISSUE TITLE
Error at start on LIbreelec 9.0.1 / Kodi 18.1

### ISSUE THREAD

**Issue by siick** [jaylinski/kodi-addon-soundcloud#2]
Hello,
I have tried your mod to at least browse tracks on Soundcloud with Kodi.
I have installed your version (master branch, Your files copied in /storage/.kodi/addons/plugin.audio.soundcloud )
but the addon failed at start. Do i miss something? 
I use LIbreelec 9.0.1 with Kodi 18.1
[kodi.log](https://github.com/jaylinski/kodi-addon-soundcloud/files/3100436/kodi.log)

**Comment by jaylinski** [comment]
@siick can you try installing the plugin via Kodi interface?

1. ![](https://images.drivereasy.com/wp-content/uploads/2018/01/img_5a4b4595de62a.jpg)
2. ![](https://images.drivereasy.com/wp-content/uploads/2017/12/img_5a409911c271c.jpg)
3. ![](https://images.drivereasy.com/wp-content/uploads/2017/12/img_5a40973062535.jpg)

By installing it this way, all plugin dependencies (like the future module) should be resolved and downloaded by Kodi.

**Comment by siick** [comment]
Yes it works this way. Sorry to have opened an issue just for that. But maybe you can add this to the README ;)

**Comment by jaylinski** [comment]
@siick no problem!

I added some install instructions: https://github.com/jaylinski/kodi-addon-soundcloud/tree/v3.0.0-alpha.1#installation
