### ISSUE TITLE
Make it possible to enter a custom OAuth token

### ISSUE THREAD

**Issue by PostnikovArtem** [jaylinski/kodi-addon-soundcloud#38]
Hello! Official tracks stop after 30 seconds of playback. This is due to the subscription. I have it on my account, how can I connect my account to your plugin? Thanks.

**Comment by jaylinski** [comment]
I think you are talking about the track previews?

It is currently not possible to login to your SoundCloud account. You can maybe work around this by entering your own client-ID in the advanced settings, but it will be overwritten on each Kodi start.

I created an issue for this: #40 

I don't have much time at the moment, so it will take some time until it is implemented.

**Comment by PostnikovArtem** [comment]
I tried to find out my client-ID and it coincided with yours. How is this possible?

**Comment by jaylinski** [comment]
The Kodi plugin extracts the client ID from the SoundCloud website. I guess that means the client-ID is irrelevant for listening to tracks that need a subscription.

In the SoundCloud web-requests, there is an Authorization header containing an OAuth token. I guess this is needed. https://developers.soundcloud.com/docs/api/guide#authentication

**Comment by PostnikovArtem** [comment]
Unfortunately, soundcloud has been banning application registration for more than a year. :(

**Comment by jaylinski** [comment]
Yep. But the SoundCloud website itself is a registered application, that's why the client-ID is extracted from there. With this client-ID a user login can be implemented.

**Comment by PostnikovArtem** [comment]
Oh, I unfortunately do not understand much about all this. I hope that you can do the authorization. Thanks for answers!

**Comment by jaylinski** [comment]
I'm closing this for now, but implementing the login is still on my roadmap. (#40)

**Comment by zedrdave** [comment]
> It is currently not possible to login to your SoundCloud account. You can maybe work around this by entering your own client-ID in the advanced settings, but it will be overwritten on each Kodi start.

Until proper login is implemented, it would be great if it was at least possible to save the Oauth token between restarts, without Kodi overwriting it. Is there a reason this cannot be done?

Also, how hard would it be to display the list of liked tracks for logged-in users?

**Comment by jaylinski** [comment]
> Until proper login is implemented, it would be great if it was at least possible to save the Oauth token between restarts, without Kodi overwriting it. Is there a reason this cannot be done?
> 
> Also, how hard would it be to display the list of liked tracks for logged-in users?

The reason: my implementation sucks (it was my first addon).

I'll try to fix it this week.

**Comment by zedrdave** [comment]
@jaylinski Thanks a lot for the quick reply!

I have zero Kodi Add-on experience, but pretty good experience coding in Python in general. If I can be of help, let me know…
