### ISSUE TITLE
Could set 'comment' as description

### ISSUE THREAD

**Issue by vyachkonovalov** [jaylinski/kodi-addon-soundcloud#44]
https://github.com/jaylinski/kodi-addon-soundcloud/blob/bdd69e5ce558da5deda6227a562636ca06bc3558/resources/lib/models/track.py#L32

https://i.imgur.com/l81rUQy.png

dk how to set info above the comment though, found nothing that works in [kodi source](https://github.com/xbmc/xbmc/blob/18.6-Leia/xbmc/music/tags/MusicInfoTag.cpp#L677)

**Comment by jaylinski** [comment]
@vyachkonovalov Thanks for the input! I'll try that.

Kodi docs: https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14

The previous plugin didn't set the comment. I don't know it there was a reason for that: 
https://github.com/SLiX69/plugin.audio.soundcloud/blob/86d219eb9ba199c568c3ddd8764d6eedcab07e56/resources/lib/nightcrawler/core/kodi/kodi_items.py#L20
