### ISSUE TITLE
Can't remotely start playing soundcloud tracks via Yatse and Play to Kodi.

### ISSUE THREAD

**Issue by Finnitio** [jaylinski/kodi-addon-soundcloud#52]
hello,  

when I have soundcloud open and select "Play Now" in "Play to Kodi" - Extension nothing happens. If I use Yatse Android app it gives me the error that it couldn't finde an appropriate addon to open within kodi.

If I reinstall soundcloud addon in kodi it starts playing a track with yatse app in "Play to Kodi" extension it doesn't. I can see a track being played in kodi and in Yatse when it's being played.

However after a while it does stop working.

**Comment by jaylinski** [comment]
Hi! I need some more information, so I can debug that issue:

* Kodi version
* Browser (Chrome, Firefox?)
* Are you sharing from the SoundCloud app or the SoundCloud website?

**Comment by Finnitio** [comment]
Kodi is Matrix

Browser os chrome

While on android I use the soundcloud app and yatse

While in windows I use chrome and Play to Kodi

**Comment by jaylinski** [comment]
@Finnitio Regarding the "Play to Kodi"-extension: it seems to be outdated and not working anymore: https://github.com/khloke/play-to-xbmc-chrome/blob/1.9.1/js/content_scripts/soundcloud-content-scripts.js
I would normally recommend to open an issue in that repository, but it seems abandoned. Maybe you can find a working Chrome extension. If you are also using Firefox, you can try https://addons.mozilla.org/en-US/firefox/addon/echo-for-kodi/.

Regarding the Yatse issue: I think that's related to #34, so you should change the audio format from `Opus (HLS)` to `mp3 (progressive)`. (You can find this settings in the SoundCloud Kodi add-on settings.)

**Comment by jmbreuer** [comment]
For the sake of discoverability, and in light of its most recent fix (getting SoundCloud to work again): I'm keeping a fork of "Play to Kodi" up to date (in the sense that I use it myself practically daily) here: https://github.com/jmbreuer/play-to-kodi-chrome

It can be installed with the "Load unpacked [Extension]" method in Chrome-based browsers.
