### ISSUE TITLE
[Bug] Discover button is not working anymore.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jaylinski/kodi-addon-soundcloud#55]
Hey there, sorry for bothering you but im having an error with Discover button  and was wondering if you could fix this bug. 

Thank you

**Comment by jaylinski** [comment]
@Goldenfreddy0703 The fix isn't released yet, see https://github.com/xbmc/repo-plugins/pull/3778.

It will probably take a day or two until the fixed version is available as an update. (You maybe also have to clear the cache in the plugin settings.)

**Comment by Goldenfreddy0703** [comment]
oh sure, i will try that, somehow mine just got fixed and idk how tbh but thank you for updating me about that.
