### ISSUE TITLE
Kodi crashes after song is finished

### ISSUE THREAD

**Issue by Miniontoby** [jaylinski/kodi-addon-soundcloud#61]
My kodi crashes every time one soundcloud song is done playing.

Since I haven't really payed attention when it happened the two times that I was listening to music on soundcloud. But what I can tell you it that it at least doesn't play the second song of the playlist/artist/search results.

----

### Technical Info

- **Kodi version**: 19 (Matrix)

- **OS**: bullseye on raspberry pi 4

- **Crashlog**: [kodi_crashlog-20231101_204248.log](https://github.com/jaylinski/kodi-addon-soundcloud/files/13238289/kodi_crashlog-20231101_204248.log)

**Comment by jaylinski** [comment]
Can you try changing the audio format in the addon settings?

**Comment by Miniontoby** [comment]
Which one should I try?

**Comment by jaylinski** [comment]
You can try "mp3 (HLS)".

**Comment by Miniontoby** [comment]
That seems to have fixed it! Thanks
